services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_NAME: "ans_database"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: